// Bundled minimal EasyMock — partial mocks with record / replay / verify,
// enough for the CSA neighborhood validators (they check that a student's
// method makes the right internal calls). Injected when a source imports
// org.easymock. The partial-mock subclasses themselves are generated by the
// compiler (it knows the mocked method names); this file holds the shared
// engine, the static API, and the __Mockable hook replay/verify use.

interface __Mockable {
  __EMockEngine __engine();
}

// Per-mock expectation engine. In record mode a mocked-method call appends an
// expectation (default return, count 1) and points the global cursor at it so
// expect(...).andReturn(...).times(...) can refine it. In replay mode a call
// consumes the next matching expectation and returns its value.
class __EMockEngine {
  boolean recording = true;
  String[] exMethod = new String[512];
  int[] exReturn = new int[512];
  Object[] exReturnObj = new Object[512];
  int[] exCount = new int[512];
  int exN = 0;

  // Record/replay a primitive-returning mocked call.
  int consume(String method) {
    if (recording) {
      exMethod[exN] = method;
      exReturn[exN] = 0;
      exReturnObj[exN] = null;
      exCount[exN] = 1;
      __EMock.current = this;
      __EMock.currentIndex = exN;
      exN++;
      return 0;
    }
    for (int i = 0; i < exN; i++) {
      if (exMethod[i].equals(method) && exCount[i] > 0) {
        exCount[i]--;
        return exReturn[i];
      }
    }
    throw new RuntimeException("unexpected call to mocked method " + method + "()");
  }

  // Record/replay a reference-returning mocked call (the recorded value comes
  // from andReturn(Object)).
  Object consumeObj(String method) {
    if (recording) {
      exMethod[exN] = method;
      exReturn[exN] = 0;
      exReturnObj[exN] = null;
      exCount[exN] = 1;
      __EMock.current = this;
      __EMock.currentIndex = exN;
      exN++;
      return null;
    }
    for (int i = 0; i < exN; i++) {
      if (exMethod[i].equals(method) && exCount[i] > 0) {
        exCount[i]--;
        return exReturnObj[i];
      }
    }
    throw new RuntimeException("unexpected call to mocked method " + method + "()");
  }

  void doReplay() {
    recording = false;
  }

  void doVerify() {
    for (int i = 0; i < exN; i++) {
      if (exCount[i] > 0) {
        throw new RuntimeException("expected more calls to " + exMethod[i] + "()");
      }
    }
  }
}

// Global cursor for the last recorded expectation (EasyMock's expect(...) is
// static and refers to the most recent mocked call).
class __EMock {
  static __EMockEngine current;
  static int currentIndex;
}

class __EMockSetter {
  __EMockEngine engine;
  int index;

  __EMockSetter(__EMockEngine engine, int index) {
    this.engine = engine;
    this.index = index;
  }

  __EMockSetter andReturn(boolean v) {
    engine.exReturn[index] = v ? 1 : 0;
    return this;
  }

  __EMockSetter andReturn(int v) {
    engine.exReturn[index] = v;
    return this;
  }

  __EMockSetter andReturn(Object v) {
    engine.exReturnObj[index] = v;
    return this;
  }

  __EMockSetter times(int n) {
    engine.exCount[index] = n;
    return this;
  }

  __EMockSetter once() {
    engine.exCount[index] = 1;
    return this;
  }
}

class EasyMock {
  static __EMockSetter expect(boolean v) {
    return new __EMockSetter(__EMock.current, __EMock.currentIndex);
  }

  static __EMockSetter expect(int v) {
    return new __EMockSetter(__EMock.current, __EMock.currentIndex);
  }

  static __EMockSetter expect(Object v) {
    return new __EMockSetter(__EMock.current, __EMock.currentIndex);
  }

  static void replay(Object mock) {
    ((__Mockable) mock).__engine().doReplay();
  }

  static void verify(Object mock) {
    ((__Mockable) mock).__engine().doVerify();
  }
}
