//! The `javac`-equivalent half of caturra: compiles Java 11 source (the
//! AP Computer Science A subset) to JVM class files.
//!
//! Pipeline: [`lexer`] → [`parser`] (AST) → [`codegen`]
//! ([`caturra_classfile::ClassFile`]). The supported language surface and
//! its staging plan live in `specs/LANGUAGE.md`; constructs beyond the
//! current stage produce friendly "not yet supported" diagnostics.

pub mod ast;
mod bridges;
mod capture;
pub mod codegen;
mod constfold;
pub mod diagnostics;
mod flow;
mod imports;
mod inner;
mod lambda;
pub mod lexer;
mod mock;
pub mod parser;
mod thrown;

use std::collections::HashMap;
use std::fmt::Write as _;

use caturra_classfile::ClassFile;

pub use codegen::{begin_type_verification, end_type_verification};
pub use diagnostics::{Diagnostic, Severity, SourcePosition, SourceSpan};

/// One Java source file presented to the compiler.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SourceFile {
    /// Path of the file, e.g. `Main.java` or `com/example/Main.java`.
    pub path: String,
    /// Full source text.
    pub text: String,
}

/// A compiled class, ready to be loaded by the VM or written to the
/// virtual filesystem as a `.class` file.
#[derive(Debug, Clone, PartialEq)]
pub struct CompiledClass {
    /// Binary class name, e.g. `com/example/Main`.
    pub binary_name: String,
    pub class_file: ClassFile,
}

/// The result of compiling a set of source files. Compilation is
/// all-or-nothing: if any error-severity diagnostic is present,
/// `classes` is empty.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct Compilation {
    pub classes: Vec<CompiledClass>,
    pub diagnostics: Vec<Diagnostic>,
    /// Entry class for a validation ("Test") run — set when `JUnit` `@Test`
    /// methods were found and a synthetic runner was injected. Run this
    /// class's `main` instead of the student's to execute the tests.
    pub validation_entry: Option<String>,
}

impl Compilation {
    /// Whether compilation succeeded (no error-severity diagnostics).
    #[must_use]
    pub fn success(&self) -> bool {
        self.diagnostics
            .iter()
            .all(|d| d.severity != Severity::Error)
    }
}

/// Bundled clean-room implementation of `org.code.neighborhood`,
/// injected when a source imports that package.
const NEIGHBORHOOD_LIB: &str = include_str!("stdlib/neighborhood.java");

/// Bundled clean-room implementation of `org.code.theater` and
/// `org.code.media`, injected when either package is imported.
const THEATER_LIB: &str = include_str!("stdlib/theater.java");

/// Bundled clean-room `javax.swing` / `java.awt` subset, injected when
/// either package is imported. The component tree serializes to the VFS
/// file `swing.json`, which the playground renders as accessible DOM.
const SWING_LIB: &str = include_str!("stdlib/swing.java");

/// Bundled `org.junit.jupiter.api.Assertions` subset, injected when a
/// source imports `org.junit` (the validation "Test" mode).
const JUNIT_LIB: &str = include_str!("stdlib/junit.java");

/// Bundled `java.util.Arrays` subset (`toString`), injected when a source
/// imports `java.util` — element concatenation coerces each via `toString`.
const ARRAYS_LIB: &str = include_str!("stdlib/arrays.java");

/// Bundled `java.lang.reflect.Modifier` subset, injected when a source uses
/// `Modifier.` (the access-flag decoder used by reflection validators).
const REFLECT_LIB: &str = include_str!("stdlib/reflect.java");

/// The JDK binary name of a bundled class that stands for a real one. Only
/// the classes a program can hold an INSTANCE of are listed: a class name is
/// observable through `getClass()` and the default `toString`, and the
/// static-only helpers (`Collections`, `Arrays`) are never instances.
fn jdk_binary_name(simple: &str) -> Option<&'static str> {
    match simple {
        "Random" => Some("java/util/Random"),
        "StringJoiner" => Some("java/util/StringJoiner"),
        _ => None,
    }
}

/// Bundled `java.util` helpers (`Random`, `Collections`), injected when a
/// source references `Random`/`Collections`.
const UTIL_LIB: &str = include_str!("stdlib/util.java");

/// The erased `__BiConsumer` target type of a `Map.forEach` lambda,
/// injected when a source calls `forEach`.
const FUNCTION_LIB: &str = include_str!("stdlib/function.java");

/// Bundled `org.code.validation` (test harness helpers), injected when a
/// source imports it: `SystemOutTestRunner`, `ValidationHelper`, and the
/// neighborhood log types.
const VALIDATION_LIB: &str = include_str!("stdlib/validation.java");

/// `NeighborhoodTestRunner`, injected only when `org.code.neighborhood` is
/// also imported (it reads `__NbhdWorld`'s action log).
const VALIDATION_NEIGHBORHOOD_LIB: &str = include_str!("stdlib/validation_neighborhood.java");

/// Bundled minimal `EasyMock` (partial mocks + record/replay/verify), injected
/// when a source imports `org.easymock`. The mock subclasses are generated by
/// the [`mock`] rewrite; this provides the engine and static API.
const EASYMOCK_LIB: &str = include_str!("stdlib/easymock.java");

/// A discovered `@Test` method for the synthetic validation runner.
struct TestCase {
    method: String,
    display: String,
    order: i32,
}

/// A test class: its `@BeforeAll`/`@BeforeEach` setup methods and ordered
/// `@Test`s.
struct TestClass {
    name: String,
    before_all: Vec<String>,
    before_each: Vec<String>,
    after_each: Vec<String>,
    after_all: Vec<String>,
    tests: Vec<TestCase>,
}

/// Collect `JUnit` `@Test` methods (with `@Order`/`@DisplayName`/`@BeforeEach`)
/// from the user's classes.
fn collect_tests(units: &[(String, ast::CompilationUnit)]) -> Vec<TestClass> {
    let mut classes = Vec::new();
    for (_, unit) in units {
        for class in &unit.classes {
            let has = |m: &ast::MethodDecl, n: &str| m.annotations.iter().any(|a| a.name == n);
            let before_all: Vec<String> = class
                .methods
                .iter()
                .filter(|m| has(m, "BeforeAll"))
                .map(|m| m.name.clone())
                .collect();
            let before_each: Vec<String> = class
                .methods
                .iter()
                .filter(|m| has(m, "BeforeEach"))
                .map(|m| m.name.clone())
                .collect();
            // `@AfterEach`/`@AfterAll` ran nowhere at all. JUnit runs the
            // teardown even when the test FAILS, and a validator that captures
            // printing restores `System.out` there — so without it every
            // verdict after the first went into the student's own buffer.
            let after_each: Vec<String> = class
                .methods
                .iter()
                .filter(|m| has(m, "AfterEach"))
                .map(|m| m.name.clone())
                .collect();
            let after_all: Vec<String> = class
                .methods
                .iter()
                .filter(|m| has(m, "AfterAll"))
                .map(|m| m.name.clone())
                .collect();
            let mut tests: Vec<TestCase> = class
                .methods
                .iter()
                .filter(|m| has(m, "Test"))
                .map(|m| {
                    let order = m
                        .annotations
                        .iter()
                        .find(|a| a.name == "Order")
                        .and_then(|a| a.int_arg)
                        .unwrap_or(i32::MAX);
                    // The label a student reads in the results panel, and JUnit
                    // is fussier about it than it looks. `@DisplayName` is
                    // TRIMMED (JUnit rejects a blank one outright), and without
                    // the annotation the default is `name()` — the parentheses
                    // are part of it. We printed the raw annotation and a bare
                    // method name, so 1721 corpus levels labelled their tests
                    // differently here than on Code.org.
                    let display = m
                        .annotations
                        .iter()
                        .find(|a| a.name == "DisplayName")
                        .and_then(|a| a.str_arg.as_deref())
                        .map(str::trim)
                        .filter(|name| !name.is_empty())
                        .map_or_else(|| format!("{}()", m.name), str::to_owned);
                    TestCase {
                        method: m.name.clone(),
                        display,
                        order,
                    }
                })
                .collect();
            tests.sort_by_key(|t| t.order);
            if !tests.is_empty() {
                classes.push(TestClass {
                    name: class.name.clone(),
                    before_all,
                    before_each,
                    after_each,
                    after_all,
                    tests,
                });
            }
        }
    }
    classes
}

/// Generate a runner `main` that instantiates each test class, runs its
/// `@BeforeEach` setup and each `@Test`, and prints one
/// `__VTEST\t<PASS|FAIL>\t<name>\t<message>` line per test.
///
/// It announces the whole roster first, one `__VPLAN\t<name>` line per test,
/// **before running any of them**. A test that a host sees planned but never
/// gets a verdict for did not run, and must be reported as a failure rather
/// than passed over — otherwise a run that dies part-way silently reports only
/// the tests that happened to finish, and a student is told everything passed.
///
/// That is not hypothetical. `catch (Throwable)` catches every Java throwable,
/// but a VM error is not one: an unsupported intrinsic, an exhausted
/// instruction budget, an interrupt — none of them can be caught by generated
/// Java, and each one used to take the rest of the roster down with it. The
/// plan lines make the roster known before anything can go wrong, so the count
/// a host reports cannot shrink.
fn validation_runner_source(classes: &[TestClass]) -> String {
    // The protocol lines go out through the stream `System.out` names at
    // startup, held in a local. A validator that captures printing —
    // `System.setOut(new PrintStream(captor))`, which is how JUnit tests check
    // console output and how two of Code.org's own validators are written —
    // would otherwise redirect the RUNNER's reporting into the student's
    // buffer, and every verdict after the first would vanish. A real harness
    // reports out of band for the same reason.
    let mut src = String::from(
        "public class __ValidationRunner {\n  public static void main(String[] args) {\n    \
         java.io.PrintStream __log = System.out;\n",
    );
    for class in classes {
        for test in &class.tests {
            let _ = writeln!(
                src,
                "    __log.println(\"__VPLAN\\t{}\");",
                escape_for_java(&test.display)
            );
        }
    }
    for class in classes {
        // `@BeforeAll` runs once (static); tolerate failure so per-test
        // errors are still reported individually.
        for setup in &class.before_all {
            src.push_str("    try {\n");
            let _ = writeln!(src, "      {}.{setup}();", class.name);
            src.push_str("    } catch (Throwable __e) {}\n");
        }
        for test in &class.tests {
            let name = escape_for_java(&test.display);
            // Each test gets its own BLOCK: the instance is declared outside
            // the `try` so the catch arm can run the teardown on it too, and
            // that declaration would otherwise collide with the next test's.
            src.push_str("    {\n");
            let _ = writeln!(src, "    {} __t = null;", class.name);
            src.push_str("    try {\n");
            let _ = writeln!(src, "      __t = new {}();", class.name);
            for setup in &class.before_each {
                let _ = writeln!(src, "      __t.{setup}();");
            }
            let _ = writeln!(src, "      __t.{}();", test.method);
            // JUnit runs the teardown whether the test passed or threw, so it
            // goes in BOTH arms — a `finally` would run after the verdict is
            // printed, which is the one order that does not work when the
            // teardown is what restores `System.out`.
            for teardown in &class.after_each {
                let _ = writeln!(
                    src,
                    "      try {{ __t.{teardown}(); }} catch (Throwable __e) {{}}"
                );
            }
            let _ = writeln!(src, "      __log.println(\"__VTEST\\tPASS\\t{name}\\t\");");
            src.push_str("    } catch (Throwable __e) {\n");
            // One line per test, so the message has to survive being put on
            // one. The corpus's failure messages are the HINT a student reads,
            // and they are written across several lines — printed raw, the line
            // ended at the first newline and the rest of the guidance was lost.
            // A null message (a bare `throw new IllegalStateException()`) is
            // empty, not the text "null".
            for teardown in &class.after_each {
                let _ = writeln!(
                    src,
                    "      if (__t != null) {{ try {{ __t.{teardown}(); }} \
                     catch (Throwable __e2) {{}} }}"
                );
            }
            src.push_str("      String __m = __e.getMessage();\n");
            src.push_str("      if (__m == null) { __m = \"\"; }\n");
            src.push_str(
                "      __m = __m.replace('\\t', ' ').replace('\\r', ' ').replace('\\n', ' ');\n",
            );
            let _ = writeln!(
                src,
                "      __log.println(\"__VTEST\\tFAIL\\t{name}\\t\" + __m);"
            );
            src.push_str("    }\n    }\n");
        }
    }
    for class in classes {
        for teardown in &class.after_all {
            let _ = writeln!(
                src,
                "    try {{ {}.{teardown}(); }} catch (Throwable __e) {{}}",
                class.name
            );
        }
    }
    src.push_str("  }\n}\n");
    src
}

/// A test's display name, safe to sit inside a Java string literal and inside
/// one tab-separated field of the runner's output.
fn escape_for_java(display: &str) -> String {
    display
        .replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace(['\t', '\n', '\r'], " ")
}

/// The student's class names: classes in the original (non-injected) sources
/// that are not `JUnit` validators. `ValidationHelper.getClassNames` reports
/// these so a validator can check the student defined a class by name.
fn student_class_names(units: &[(String, ast::CompilationUnit)]) -> Vec<String> {
    let mut names = Vec::new();
    for (path, unit) in units {
        if path.starts_with('<') {
            continue; // injected bundle / synthetic unit
        }
        let is_validator = unit.imports.iter().any(|import| {
            import.path.first().map(String::as_str) == Some("org")
                && import.path.get(1).map(String::as_str) == Some("junit")
        });
        if is_validator {
            continue;
        }
        for class in &unit.classes {
            names.push(class.name.clone());
        }
    }
    names
}

/// Generate the `__ValidationClasses` companion that backs
/// `ValidationHelper.getClassNames` with a compile-time class-name list.
fn user_classes_source(names: &[String]) -> String {
    let mut src = String::from(
        "class __ValidationClasses {\n  \
         static java.util.ArrayList<String> names() {\n    \
         java.util.ArrayList<String> n = new java.util.ArrayList<String>();\n",
    );
    for name in names {
        // Class names are identifiers, so no escaping is needed.
        let _ = writeln!(src, "    n.add(\"{name}\");");
    }
    src.push_str("    return n;\n  }\n}\n");
    src
}

/// Whether any unit imports something under the given prefix path
/// (`["org","junit"]` matches `import static org.junit.jupiter....`).
fn imports_prefix(units: &[(String, ast::CompilationUnit)], prefix: &[&str]) -> bool {
    units.iter().any(|(_, unit)| {
        unit.imports.iter().any(|import| {
            import.path.len() >= prefix.len() && import.path[..prefix.len()] == *prefix
        })
    })
}

/// Whether any unit imports a class from the given package path
/// (matches both `import pkg.*` and `import pkg.Class`).
fn imports_package(units: &[(String, ast::CompilationUnit)], package: &[&str]) -> bool {
    units.iter().any(|(_, unit)| {
        unit.imports.iter().any(|import| {
            let prefix = if import.wildcard {
                import.path.as_slice()
            } else {
                &import.path[..import.path.len().saturating_sub(1)]
            };
            prefix == package
        })
    })
}

/// Every `a.b.c` chain of identifiers in a token stream. Bundled library
/// sources are injected only when a program reaches for the package — and a
/// FULLY QUALIFIED name reaches for it without an import, which is the whole
/// point of writing one. Read off the tokens rather than the source text so a
/// package named in a comment or a string literal does not pull a library in.
fn qualified_chains(tokens: &[lexer::Token]) -> Vec<Vec<String>> {
    let mut chains = Vec::new();
    let mut index = 0;
    while index < tokens.len() {
        let lexer::TokenKind::Identifier(first) = &tokens[index].kind else {
            index += 1;
            continue;
        };
        let mut chain = vec![first.clone()];
        index += 1;
        while index + 1 < tokens.len()
            && tokens[index].kind == lexer::TokenKind::Symbol(".")
            && let lexer::TokenKind::Identifier(next) = &tokens[index + 1].kind
        {
            chain.push(next.clone());
            index += 2;
        }
        if chain.len() > 1 {
            chains.push(chain);
        }
    }
    chains
}

/// Whether a program reaches for `package` at all: by importing it, or by
/// naming one of its classes in full. A fully qualified name needs no import
/// in Java, so gating the bundled sources on the import alone refused
/// `org.code.neighborhood.Painter p = new org.code.neighborhood.Painter()`
/// with the false claim that Painter is not supported.
fn reaches_package(
    units: &[(String, ast::CompilationUnit)],
    chains: &[Vec<String>],
    package: &[&str],
) -> bool {
    imports_package(units, package) || uses_package_qualified(chains, package)
}

/// Whether any source names a class in `package` by its qualified name.
fn uses_package_qualified(chains: &[Vec<String>], package: &[&str]) -> bool {
    chains.iter().any(|chain| {
        chain.len() > package.len()
            && chain
                .iter()
                .zip(package)
                .all(|(segment, expected)| segment == expected)
    })
}

/// Compile a set of Java source files. All files are parsed first so
/// classes can call each other's static methods regardless of file
/// The name prefix of a class synthesized for a LAMBDA. Several passes key
/// on it: a lambda has no `this` of its own, and its bare names resolve in
/// the enclosing scope.
pub(crate) const LAMBDA_CLASS_PREFIX: &str = "Lambda$";

/// The prefix for a class synthesized from a METHOD REFERENCE. It behaves
/// like a lambda everywhere except capture: JLS §15.13.3 evaluates the
/// receiver when the reference is created, so the variable it came from need
/// not be effectively final.
pub(crate) const METHOD_REF_CLASS_PREFIX: &str = "MethodRef$";

/// Whether a class name is one of the synthesized function classes.
/// A synthesized METHOD-REFERENCE class — the body of a `Type::method`.
pub(crate) fn is_method_ref_class(name: &str) -> bool {
    name.starts_with(METHOD_REF_CLASS_PREFIX)
}

pub(crate) fn is_lambda_class(name: &str) -> bool {
    name.starts_with(LAMBDA_CLASS_PREFIX) || name.starts_with(METHOD_REF_CLASS_PREFIX)
}

/// order.
#[must_use]
#[allow(clippy::too_many_lines)] // the bundle-injection pipeline
pub fn compile(sources: &[SourceFile]) -> Compilation {
    let mut compilation = Compilation::default();
    let mut seen: HashMap<String, String> = HashMap::new();
    let mut units = Vec::new();
    let mut chains = Vec::new();

    for source in sources {
        let (tokens, mut lex_errors) = lexer::lex(&source.path, &source.text);
        chains.append(&mut qualified_chains(&tokens));

        let (unit, mut parse_errors) = parser::parse(&source.path, tokens);
        // A syntax error AT a lexical one is that lexical one, told twice: the
        // parser is handed a token the lexer has already complained about and
        // says what it cannot do with it. javac reports only the first —
        // `int x = 1_;` is "illegal underscore", not that plus "expected an
        // expression" pointing at the same `;`. A LATER syntax error is a
        // separate mistake and stays (javac reports both for `1_;` on one line
        // and a `int y = ;` on another), so the test is the POSITION, not the
        // file.
        let lex_ends: Vec<SourcePosition> = lex_errors
            .iter()
            .filter(|d| matches!(d.severity, Severity::Error))
            .filter_map(|d| d.span.map(|span| span.end))
            .collect();
        parse_errors.retain(|d| {
            d.span
                .is_none_or(|span| !lex_ends.iter().any(|end| span.start <= *end))
        });
        compilation.diagnostics.append(&mut lex_errors);
        compilation.diagnostics.append(&mut parse_errors);

        for class in &unit.classes {
            // JLS §7.6: a public top-level type must be declared in a file
            // named after it. javac enforces this, so a program that ignores
            // it compiles here and fails on a real JDK. Only user files are
            // checked — the bundled libraries declare no public types.
            if class.is_public && !class.is_anonymous && !class.is_nested {
                let base = source
                    .path
                    .rsplit('/')
                    .next()
                    .unwrap_or(&source.path)
                    .strip_suffix(".java");
                if let Some(base) = base
                    && base != class.name
                {
                    let kind = if class.is_interface {
                        "interface"
                    } else if class.is_enum {
                        "enum"
                    } else {
                        "class"
                    };
                    compilation.diagnostics.push(Diagnostic {
                        severity: Severity::Error,
                        message: format!(
                            "{kind} {} is public, should be declared in a file named {}.java",
                            class.name, class.name
                        ),
                        path: source.path.clone(),
                        span: Some(class.span),
                    });
                }
            }
            // Two classes clash only if their BINARY names do: a nested
            // `Holder.Node` is `Holder$Node`, so it may sit beside a top-level
            // `Node` exactly as it may in Java.
            let binary = class
                .binary_name
                .clone()
                .unwrap_or_else(|| class.name.clone());
            if let Some(other_path) = seen.get(&binary) {
                compilation.diagnostics.push(Diagnostic {
                    severity: Severity::Error,
                    message: format!("class '{}' is already defined in {other_path}", class.name),
                    path: source.path.clone(),
                    span: Some(class.span),
                });
            } else {
                seen.insert(binary, source.path.clone());
            }
        }
        units.push((source.path.clone(), unit));
    }

    // Auto-inject bundled library sources when their package is
    // imported (e.g. the Code.org neighborhood Painter). Parsed like
    // any other unit so its classes participate in resolution.
    if reaches_package(&units, &chains, &["org", "code", "neighborhood"]) {
        let (tokens, _) = lexer::lex("<neighborhood>", NEIGHBORHOOD_LIB);
        let (unit, mut errs) = parser::parse("<neighborhood>", tokens);
        compilation.diagnostics.append(&mut errs);
        units.push((String::from("<neighborhood>"), unit));
    }
    // org.code.validation (neighborhood test harness): runs the student's main
    // and reports the recorded action log. Depends on __NbhdWorld above.
    if reaches_package(&units, &chains, &["org", "code", "validation"]) {
        let (tokens, _) = lexer::lex("<validation-lib>", VALIDATION_LIB);
        let (unit, mut errs) = parser::parse("<validation-lib>", tokens);
        compilation.diagnostics.append(&mut errs);
        units.push((String::from("<validation-lib>"), unit));
        // The neighborhood harness depends on __NbhdWorld; only inject it when
        // the neighborhood library is present too.
        if reaches_package(&units, &chains, &["org", "code", "neighborhood"]) {
            let (tokens, _) = lexer::lex("<validation-nbhd>", VALIDATION_NEIGHBORHOOD_LIB);
            let (unit, mut errs) = parser::parse("<validation-nbhd>", tokens);
            compilation.diagnostics.append(&mut errs);
            units.push((String::from("<validation-nbhd>"), unit));
        }
        // Bake the student's class names in for `ValidationHelper.getClassNames`
        // (the student sources are the non-injected, non-JUnit units).
        let source = user_classes_source(&student_class_names(&units));
        let (tokens, _) = lexer::lex("<validation-classes>", &source);
        let (unit, mut errs) = parser::parse("<validation-classes>", tokens);
        compilation.diagnostics.append(&mut errs);
        units.push((String::from("<validation-classes>"), unit));
    }
    if reaches_package(&units, &chains, &["org", "code", "theater"])
        || reaches_package(&units, &chains, &["org", "code", "media"])
    {
        let (tokens, _) = lexer::lex("<theater>", THEATER_LIB);
        let (unit, mut errs) = parser::parse("<theater>", tokens);
        compilation.diagnostics.append(&mut errs);
        units.push((String::from("<theater>"), unit));
    }
    // javax.swing / java.awt (accessible DOM Swing): the component tree
    // serializes to `swing.json` on `setVisible(true)`.
    if reaches_package(&units, &chains, &["javax", "swing"])
        || reaches_package(&units, &chains, &["javax", "swing", "event"])
        || reaches_package(&units, &chains, &["javax", "swing", "border"])
        || reaches_package(&units, &chains, &["javax", "swing", "text"])
        || reaches_package(&units, &chains, &["javax", "accessibility"])
        || reaches_package(&units, &chains, &["java", "awt"])
        || reaches_package(&units, &chains, &["java", "awt", "event"])
    {
        let (tokens, _) = lexer::lex("<swing>", SWING_LIB);
        let (unit, mut errs) = parser::parse("<swing>", tokens);
        compilation.diagnostics.append(&mut errs);
        units.push((String::from("<swing>"), unit));
    }
    let mut validation_entry = None;
    if sources.iter().any(|s| s.text.contains("Arrays."))
        && !units
            .iter()
            .any(|(_, unit)| unit.classes.iter().any(|c| c.name == "Arrays"))
    {
        let (tokens, _) = lexer::lex("<arrays>", ARRAYS_LIB);
        let (unit, mut errs) = parser::parse("<arrays>", tokens);
        compilation.diagnostics.append(&mut errs);
        units.push((String::from("<arrays>"), unit));
    }
    if sources.iter().any(|s| s.text.contains("Modifier."))
        && !units
            .iter()
            .any(|(_, unit)| unit.classes.iter().any(|c| c.name == "Modifier"))
    {
        let (tokens, _) = lexer::lex("<reflect>", REFLECT_LIB);
        let (unit, mut errs) = parser::parse("<reflect>", tokens);
        compilation.diagnostics.append(&mut errs);
        units.push((String::from("<reflect>"), unit));
    }
    // Set when an injected library needs the functional interfaces itself.
    let mut needs_function_lib = false;
    if (sources.iter().any(|s| s.text.contains("Random"))
        // `Collections::unmodifiableSet` names the class without a dot after
        // it — the sniff missed the METHOD-REFERENCE spelling entirely, so the
        // bundle stayed out and the reference was "cannot find symbol", the
        // same shape the function bundle's `->`/`::` sniff had.
        || sources
            .iter()
            .any(|s| s.text.contains("Collections.") || s.text.contains("Collections::"))
        || sources.iter().any(|s| s.text.contains("StringJoiner")))
        && !units.iter().any(|(_, unit)| {
            unit.classes
                .iter()
                .any(|c| c.name == "Random" || c.name == "Collections" || c.name == "StringJoiner")
        })
    {
        let (tokens, _) = lexer::lex("<util>", UTIL_LIB);
        let (mut unit, mut errs) = parser::parse("<util>", tokens);
        compilation.diagnostics.append(&mut errs);
        // These two STAND FOR JDK classes, so they carry the JDK's binary
        // names: `new Random(1).getClass().getName()` is `java.util.Random`,
        // and a default `toString` prints it. Only the injected ones are
        // renamed — a program may declare its own `Random`, and that one is
        // its own class (this library is not injected beside it).
        for class in &mut unit.classes {
            if let Some(binary) = jdk_binary_name(&class.name) {
                class.binary_name = Some(String::from(binary));
            }
        }
        units.push((String::from("<util>"), unit));
        // The bundled `Random` builds its stream factories out of LAMBDAS, so
        // the functional interfaces they desugar to have to come with it. The
        // trigger below reads the USER's text, which says nothing about what
        // an injected library needs — `new Random(1).ints(3, 0, 10)` was
        // "cannot find symbol: class __Supplier", about a class no program
        // mentions.
        needs_function_lib = true;
    }
    if (needs_function_lib
        || sources.iter().any(|s| {
            s.text.contains(".forEach(")
            || s.text.contains(".forEachRemaining(")
            || s.text.contains(".removeIf(")
            || s.text.contains(".replaceAll(")
            || s.text.contains(".sort(")
            // The JDK-8 map lambda methods desugar to the bundled
            // `__BiFunction`/`__UnaryOperator`.
            || s.text.contains(".merge(")
            || s.text.contains(".compute")
            // `optional.ifPresent(x -> ...)` / `filter(x -> ...)` desugar to the
            // bundled `__Consumer`/`__Predicate` too.
            || s.text.contains(".ifPresent(")
            || s.text.contains(".filter(")
            // `Arrays.setAll(a, i -> ...)` uses the bundled `__UnaryOperator`.
            || s.text.contains(".setAll(")
            // `optional.map(x -> ...)` / `orElseGet(() -> ...)` use the bundled
            // `__UnaryOperator` / `__Supplier`.
            || s.text.contains(".map(")
            || s.text.contains(".orElseGet(")
            // `optional.or(() -> ...)` and `ifPresentOrElse(x -> …, () -> …)`
            // (Java 9) desugar to the bundled `__Supplier`/`__Consumer`/
            // `__Runnable`, and spell none of the words above: without the
            // bundle the interface the desugaring targets did not exist, and
            // the program was refused with "cannot find symbol: class
            // __Supplier" — a name it never wrote.
            || s.text.contains(".or(")
            || s.text.contains(".ifPresentOrElse(")
            // A stream pipeline's `filter`/`map`/… lambdas desugar to the
            // bundled functional interfaces.
            || s.text.contains(".stream(")
            || s.text.contains("Stream")
            // A user `Comparator` aliases the bundled `__Comparator` interface;
            // `Collections.reverseOrder()` also yields one without naming it.
            || s.text.contains("Comparator")
            || s.text.contains("reverseOrder")
            // `Map.Entry.comparingByKey()` / `comparingByValue()` yield one
            // while naming neither `Comparator` nor any word above, so a
            // program that sorts entries and nothing else had no bundle: the
            // comparator's own TYPE was unknown, and `new TreeSet<>(
            // Map.Entry.comparingByKey())` was refused as "takes a Collection
            // or a Comparator" — about a Comparator.
            || s.text.contains("comparingBy")
            // ...and so does `String.CASE_INSENSITIVE_ORDER`, whose TYPE is a
            // `Comparator<String>` the program never spells. Without the
            // bundle its type was unknown, so calling `compare` on it was
            // refused in a program that names `java.util` nowhere.
            || s.text.contains("CASE_INSENSITIVE_ORDER")
            // The `java.util.function` interfaces alias the bundled erased ones.
            || s.text.contains("java.util.function")
            || s.text.contains("Function")
            || s.text.contains("Predicate")
            || s.text.contains("Supplier")
            || s.text.contains("Consumer")
            || s.text.contains("Runnable")
            // `IntUnaryOperator` and the other primitive specializations spell
            // none of the words above.
            || s.text.contains("Operator")
            // A comparator in a sorted collection's constructor
            // (`new PriorityQueue<>((a, b) -> ...)`) needs `__Comparator` too,
            // without ever naming it — trigger on the pair. A method
            // REFERENCE is the same comparator with no arrow in it
            // (`new TreeMap<>(String::compareTo)`), and spelled that way the
            // bundle was left out: the interface the desugaring targets did
            // not exist, and the program was refused for a class it never
            // wrote.
            || ((s.text.contains("->") || s.text.contains("::"))
                && (s.text.contains("TreeSet")
                    || s.text.contains("TreeMap")
                    || s.text.contains("PriorityQueue")))
            // …and so does one handed to `Collections.max`/`min`/
            // `binarySearch`, which name neither the interface nor `sort`.
            || ((s.text.contains("->") || s.text.contains("::"))
                && (s.text.contains(".max(")
                    || s.text.contains(".min(")
                    || s.text.contains(".binarySearch(")))
        }))
        && !units
            .iter()
            .any(|(_, unit)| unit.classes.iter().any(|c| c.name == "__BiConsumer"))
    {
        let (tokens, _) = lexer::lex("<function>", FUNCTION_LIB);
        let (unit, mut errs) = parser::parse("<function>", tokens);
        compilation.diagnostics.append(&mut errs);
        units.push((String::from("<function>"), unit));
    }
    if imports_prefix(&units, &["org", "junit"]) {
        let (tokens, _) = lexer::lex("<junit>", JUNIT_LIB);
        let (unit, mut errs) = parser::parse("<junit>", tokens);
        compilation.diagnostics.append(&mut errs);
        units.push((String::from("<junit>"), unit));
        // Synthesize a runner that executes the discovered @Test methods.
        let tests = collect_tests(&units);
        if !tests.is_empty() {
            let source = validation_runner_source(&tests);
            let (tokens, _) = lexer::lex("<validation>", &source);
            let (unit, mut errs) = parser::parse("<validation>", tokens);
            compilation.diagnostics.append(&mut errs);
            units.push((String::from("<validation>"), unit));
            validation_entry = Some(String::from("__ValidationRunner"));
        }
    }

    // EasyMock partial mocks: inject the engine, then rewrite each
    // `partialMockBuilder(T.class)….createMock()` chain into a generated
    // `new __EMock_T_…()` subclass (before codegen or import checks see them).
    if imports_prefix(&units, &["org", "easymock"]) {
        let (tokens, _) = lexer::lex("<easymock>", EASYMOCK_LIB);
        let (unit, mut errs) = parser::parse("<easymock>", tokens);
        compilation.diagnostics.append(&mut errs);
        units.push((String::from("<easymock>"), unit));
        if let Some(source) = mock::rewrite(&mut units) {
            let (tokens, _) = lexer::lex("<mocks>", &source);
            let (unit, mut errs) = parser::parse("<mocks>", tokens);
            compilation.diagnostics.append(&mut errs);
            units.push((String::from("<mocks>"), unit));
        }
    }

    // Import validation and enforcement (after all units parse, since
    // user classes anywhere in the compilation shadow library names).
    //
    // Only classes the PROGRAM declares shadow a library name. A bundled
    // library is lexed under `<name>`, and counting its classes here made
    // every name it declares exempt from the import rule — so `Random r = new
    // Random(1)` with no `import java.util.Random` compiled, and a JDK refuses
    // it. Bundled units are not checked either: they have no imports of their
    // own, and they are not the program's code.
    let user_classes: std::collections::HashSet<String> = units
        .iter()
        .filter(|(path, _)| !path.starts_with('<'))
        .flat_map(|(_, unit)| unit.classes.iter().map(|c| c.name.clone()))
        .collect();
    // Everything from here on ATTRIBUTES the tree, and javac attributes
    // nothing that did not parse: a file with a syntax error is reported with
    // its syntax errors alone. caturra's parser recovers and carries on, so a
    // stray `int y = ;` was followed by whatever the recovered tree then made
    // of the rest — errors javac never prints, and which a student cannot act
    // on because the real mistake is the one above them.
    //
    // Taken BEFORE the import check, which is attribution too. Reading it
    // after meant an unimported class — `Pattern p = Pattern.compile("a")`
    // with no `import java.util.regex.Pattern` — made this false, and every
    // other mistake in the file was then truncated away: javac reported four
    // errors for such a program and caturra reported the import's two.
    let parsed_cleanly = !compilation
        .diagnostics
        .iter()
        .any(|d| matches!(d.severity, Severity::Error));
    let after_parse = compilation.diagnostics.len();

    for (path, unit) in &units {
        if path.starts_with('<') {
            continue;
        }
        imports::check_unit(path, unit, &user_classes, &mut compilation.diagnostics);
    }

    bridges::add_bridge_methods(&mut units);
    inner::bind_inner_classes(&mut units);
    compilation
        .diagnostics
        .extend(lambda::desugar_lambdas(&mut units));
    compilation
        .diagnostics
        .extend(capture::resolve_captures(&mut units));
    let (classes, mut codegen_errors) = codegen::generate(&units);
    compilation.diagnostics.append(&mut codegen_errors);
    if parsed_cleanly {
        flow::drop_flow_errors_after_other_errors(&mut compilation.diagnostics);
    } else {
        compilation.diagnostics.truncate(after_parse);
    }
    // The SAME complaint at the SAME place, twice. javac never prints one
    // twice, and a desugaring that expands one construct into several — a
    // try-with-resources becomes a body plus two `close()` calls — checked its
    // resource in each copy, so a student saw one mistake reported three
    // times.
    // javac attributes a file in SOURCE ORDER, so its errors come out that
    // way; caturra runs several passes over the whole file, so an import
    // error (checked first) sorted ahead of an attribution error on an
    // earlier line. Truncation used to hide that — the import error dropped
    // everything after it — and with the truncation gone the order shows.
    // A stable sort by position leaves two complaints about the same place in
    // the order the phases found them.
    compilation.diagnostics.sort_by_key(|d| {
        (
            d.path.clone(),
            d.span.map_or((0, 0), |s| (s.start.line, s.start.column)),
        )
    });
    let mut seen = std::collections::HashSet::new();
    compilation.diagnostics.retain(|d| {
        let at = d
            .span
            .map(|s| (s.start.line, s.start.column, s.end.line, s.end.column));
        seen.insert((d.message.clone(), d.path.clone(), at))
    });

    if compilation.success() {
        compilation.classes = classes;
        compilation.validation_entry = validation_entry;
    }
    compilation
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn lexical_errors_are_reported_with_positions() {
        let result = compile(&[SourceFile {
            path: String::from("Main.java"),
            text: String::from("class Main { char c = 'x; }"),
        }]);
        assert!(!result.success());
        assert!(result.classes.is_empty());
        let error = &result.diagnostics[0];
        assert_eq!(error.path, "Main.java");
        assert!(
            error.message.contains("character literal"),
            "{}",
            error.message
        );
    }

    #[test]
    fn structural_reflection_compiles() {
        // The `AttributesHelper` surface: getClass / getSimpleName /
        // getSuperclass / getDeclaredFields + Arrays.toString(Field[]).
        let result = compile(&[
            SourceFile {
                path: String::from("Dog.java"),
                text: String::from("public class Dog { private String name; private int age; }"),
            },
            SourceFile {
                path: String::from("Main.java"),
                text: String::from(
                    r#"
                    import java.lang.reflect.*;
                    import java.util.*;
                    public class Main {
                        public static void main(String[] args) {
                            Object o = new Dog();
                            Class c = o.getClass();
                            String n = c.getSimpleName();
                            Class sup = c.getSuperclass();
                            Field[] fields = c.getDeclaredFields();
                            System.out.println(n + " extends " + sup.getSimpleName());
                            System.out.println(Arrays.toString(fields));
                        }
                    }
                    "#,
                ),
            },
        ]);
        assert!(result.success(), "{:?}", result.diagnostics);
    }

    #[test]
    fn hello_world_compiles_to_a_class() {
        let result = compile(&[SourceFile {
            path: String::from("Main.java"),
            text: String::from(
                r#"
                public class Main {
                    public static void main(String[] args) {
                        System.out.println("Hello, World!");
                    }
                }
                "#,
            ),
        }]);
        assert!(result.success(), "{:?}", result.diagnostics);
        assert_eq!(result.classes.len(), 1);
        assert_eq!(result.classes[0].binary_name, "Main");
        // The class file is structurally valid: it round-trips.
        let bytes = caturra_classfile::write_class_file(&result.classes[0].class_file);
        let parsed = caturra_classfile::read_class_file(&bytes).expect("valid class file");
        assert_eq!(parsed.class_name(), Some("Main"));
    }

    #[test]
    fn duplicate_classes_across_files_are_reported() {
        let result = compile(&[
            SourceFile {
                path: "A.java".into(),
                text: "class Main { }".into(),
            },
            SourceFile {
                path: "B.java".into(),
                text: "class Main { }".into(),
            },
        ]);
        assert!(!result.success());
        assert!(
            result.diagnostics[0]
                .message
                .contains("already defined in A.java")
        );
    }

    /// caturra targets the Java 11 subset, so an API added later must be
    /// rejected exactly as javac 11 rejects it. Accepting it would be worse than
    /// missing it: the student's code compiles here and fails on a real JDK.
    #[test]
    fn post_java_11_apis_are_not_offered() {
        // Math.absExact is Java 15; Random.nextInt(origin, bound) is Java 17.
        // Both messages match what javac 11 prints for the same source.
        let cases = [
            (
                "class Main { static void run() { int x = Math.absExact(-5); } }",
                "cannot find symbol",
            ),
            (
                "import java.util.Random; \
                 class Main { static void run() { int x = new Random(1).nextInt(2, 5); } }",
                "no suitable method found for nextInt(int,int)",
            ),
        ];
        for (source, want) in cases {
            let result = compile(&[SourceFile {
                path: String::from("Main.java"),
                text: String::from(source),
            }]);
            assert!(!result.success(), "should not compile: {source}");
            let message = &result.diagnostics[0].message;
            assert!(message.contains(want), "expected {want:?}, got: {message}");
        }
    }

    /// `type_of`'s contract is that it "must agree with what `expr` leaves on
    /// the stack", and for most of this compiler's life nothing checked it.
    /// Three separate defects came from the two paths disagreeing, one of
    /// which made a whole statement vanish — no code, no value, no diagnostic.
    ///
    /// The invariant needs no oracle, so it is asserted here over the shapes
    /// that have broken it before: a qualified static as an argument, a call
    /// to an enclosing static from inside a lambda, and a reflective `invoke`
    /// whose result is passed on. The corpus and the differential suite can be
    /// swept the same way with `CATURRA_VERIFY_TYPES=1`.
    #[test]
    fn type_of_agrees_with_what_is_emitted() {
        let sources = [
            "import java.util.*;\npublic class A { static void p(Object v) {} \
             public static void main(String[] a) { p(java.util.Objects.toString(\"q\")); \
             p(java.util.List.of(1)); p(Arrays.asList(\"a\").size()); } }",
            "import java.util.function.Supplier;\npublic class B { static String w(String s) \
             { return s; } static StringBuilder of(String s) { return new StringBuilder(s); } \
             static void run(Supplier<Object> b) {} public static void main(String[] a) \
             { String s = \"x\"; run(() -> w(of(s).reverse().toString())); } }",
            "import java.lang.reflect.Method;\npublic class C { static int v() { return 7; } \
             static void p(Object o) {} public static void main(String[] a) throws Exception \
             { Method m = C.class.getDeclaredMethod(\"v\"); p(m.invoke(null)); \
             System.out.println(m.invoke(null)); } }",
            "import java.util.*;\npublic class D { public static void main(String[] a) { \
             Map<String, List<Integer>> m = new HashMap<>(); m.put(\"k\", new ArrayList<>()); \
             for (Map.Entry<String, List<Integer>> e : m.entrySet()) \
             { System.out.println(e.getKey() + e.getValue().size()); } \
             List<String> l = Arrays.asList(\"b\", \"a\"); Collections.sort(l); \
             System.out.println(String.join(\",\", l) + l.stream().count()); } }",
            // The FACTORY literals, whose element is the join of every
            // argument. That join was written three times — the emitter, the
            // `type_of` mirror and `var` inference — and the copies disagreed
            // about `List.of(1, 2.5)`: one said `Integer`, another `Number`.
            // A lone PRIMITIVE array is one element, which the join must not
            // spread.
            "import java.util.*;\npublic class E { static void p(Object o) {} \
             public static void main(String[] a) { p(Arrays.asList(1, 2.5)); \
             p(List.of(1, 2.5)); p(Map.of(\"k\", 1)); var v = List.of(1, 2.5); \
             p(v); int[] prim = {1, 2, 3}; p(Arrays.asList(prim).size()); \
             String[] refs = {\"a\"}; p(Arrays.asList(refs).size()); } }",
            // The kinds a collection can be built as, and the arrays of them.
            // `new LinkedHashMap<>()` typed as an error here while it emitted
            // a map, and `new List[n]` as an error while it emitted `Object[]`.
            "import java.util.*;\npublic class F { static void p(Object o) {} \
             public static void main(String[] a) { Map<String, Integer> m = new LinkedHashMap<>(); \
             Set<String> s = new LinkedHashSet<>(); p(m); p(s); \
             List<String>[] buckets = new List[2]; buckets[0] = new ArrayList<>(); \
             p(buckets[0]); p(buckets.length); \
             p(Optional.ofNullable(null).orElse(\"d\")); } }",
        ];
        begin_type_verification();
        for (index, text) in sources.iter().enumerate() {
            let name = ["A", "B", "C", "D", "E", "F"][index];
            let result = compile(&[SourceFile {
                path: format!("{name}.java"),
                text: (*text).to_string(),
            }]);
            assert!(result.success(), "{name}: {:?}", result.diagnostics);
        }
        let mismatches = end_type_verification();
        assert!(mismatches.is_empty(), "{mismatches:#?}");
    }

    /// A conversion `widens` allows must not be refused by the assignment
    /// matrix. The two gate separately — the source says so, and records the
    /// trap catching it twice ("the same trap that once left List -> Collection
    /// widening half-implemented"); it caught a third case this session, an
    /// array of collections. The matrix's refusal arm now asks `widens` and
    /// reports when the two disagree, so this compiles the conversion surface
    /// and lets that check speak.
    #[test]
    fn a_widening_conversion_is_never_refused() {
        let source = "import java.util.*;\nimport java.util.function.*;\n\
             import java.util.stream.*;\npublic class Conv {\n\
             interface Shape {}\n\
             static class Circle implements Shape {}\n\
             public static void main(String[] a) {\n\
             Object o = \"s\"; Object o2 = new ArrayList<String>(); Shape sh = new Circle();\n\
             Comparable<String> c = \"x\"; CharSequence cs = \"y\";\n\
             CharSequence cs2 = new StringBuilder();\n\
             List<String> l = new ArrayList<>(); Collection<String> col = l;\n\
             Iterable<String> it = l; Set<String> st = new HashSet<>();\n\
             Collection<String> col2 = st; Map<String, Integer> m = new TreeMap<>();\n\
             Queue<Integer> q = new LinkedList<>(); Deque<Integer> dq = new ArrayDeque<>();\n\
             Collection<Integer> col3 = new PriorityQueue<>();\n\
             Object[] oa = new String[1]; Object oo = new int[1];\n\
             Integer[] boxes = new Integer[1]; Object[] oa2 = boxes;\n\
             List<String>[] buckets = new List[1]; Object[] oa3 = buckets;\n\
             long lg = 5; double d = 5; float f = 5L; int i = 'c'; double d2 = 5f;\n\
             Integer bi = 5; Double bd = 1.5; Object ob = 7; Number n = 3; Number n2 = 1.5;\n\
             Comparable<Integer> ci = 5;\n\
             Runnable r = () -> {}; Supplier<String> s = () -> \"x\";\n\
             Stream<String> str = Stream.of(\"a\"); IntStream is = IntStream.of(1);\n\
             String ns = null; int[] na = null; List<String> nl = null;\n\
             }\n}";
        begin_type_verification();
        let result = compile(&[SourceFile {
            path: String::from("Conv.java"),
            text: String::from(source),
        }]);
        assert!(result.success(), "{:?}", result.diagnostics);
        let mismatches = end_type_verification();
        assert!(mismatches.is_empty(), "{mismatches:#?}");
    }

    /// Every `java.util.function` interface caturra NAMES must also have an
    /// erased interface and a SAM shape — three separate lists, in three
    /// files, that a program experiences as one fact. When they disagreed the
    /// symptom was a type a program could WRITE in a declaration and then
    /// could not use: "java.util.function.ObjIntConsumer is not supported by
    /// caturra", which reads as a deliberate gap rather than an oversight.
    #[test]
    fn every_named_functional_interface_is_usable() {
        use crate::ast::TypeRef;
        let object = || TypeRef::Named(String::from("Object"));
        for name in imports::JAVA_UTIL_FUNCTION {
            assert!(
                codegen::functional_erased(name).is_some(),
                "{name} is nameable but has no erased interface"
            );
            // The SAM is found either as an unparameterized name or at one of
            // the arities the interface takes; WHICH one is the interface's own
            // business, having none of them is the bug.
            let named = TypeRef::Named((*name).to_owned());
            let found = lambda::functional_lambda_spec(&named).is_some()
                || (1..=3).any(|arity| {
                    lambda::functional_lambda_spec(&TypeRef::Generic {
                        base: (*name).to_owned(),
                        args: vec![object(); arity],
                    })
                    .is_some()
                });
            assert!(found, "{name} is nameable but has no SAM shape");
        }
    }

    /// The two DESCRIPTOR builders must agree: one reads the written
    /// `TypeRef` (the signature the class file carries), the other the
    /// resolved `JType` (which every call site uses). When they differ the
    /// call names a method that was never emitted — "malformed class Main: no
    /// static method f(Ljava/util/Iterator;)", which is how `Iterator<T>` in a
    /// signature failed, found by hand rather than by a check.
    ///
    /// Swept the same way as the type invariant: `CATURRA_VERIFY_TYPES=1` over
    /// the corpus and the differential suite, both of which report none. These
    /// are the signature shapes that have to keep agreeing.
    #[test]
    fn a_signature_descriptor_agrees_with_its_type() {
        let source = "import java.util.*;\nimport java.util.function.*;\n\
             import java.util.stream.*;\npublic class Sig {\n\
             static String first(Iterator<String> it) { return it.next(); }\n\
             static Iterator<String> make(List<String> l) { return l.iterator(); }\n\
             static long count(Stream<String> s) { return s.count(); }\n\
             static int total(IntStream s) { return s.sum(); }\n\
             static double sum(DoubleStream s) { return s.sum(); }\n\
             static Map.Entry<String, Integer> entry() { return Map.entry(\"k\", 1); }\n\
             static String key(Map.Entry<String, Integer> e) { return e.getKey(); }\n\
             static int apply(IntUnaryOperator f) { return f.applyAsInt(1); }\n\
             static Optional<String> opt() { return Optional.of(\"x\"); }\n\
             static Set<String> set(Collection<String> c) { return new HashSet<>(c); }\n\
             static StringBuilder build(CharSequence cs) { return new StringBuilder(cs); }\n\
             static int[] ints() { return new int[0]; }\n\
             static Integer[] boxes() { return new Integer[0]; }\n\
             public static void main(String[] a) {}\n}";
        begin_type_verification();
        let result = compile(&[SourceFile {
            path: String::from("Sig.java"),
            text: String::from(source),
        }]);
        assert!(result.success(), "{:?}", result.diagnostics);
        let mismatches = end_type_verification();
        assert!(mismatches.is_empty(), "{mismatches:#?}");
    }

    /// A real Java 11 member caturra cannot model says so, rather than
    /// pretending it never existed.
    #[test]
    fn string_builder_capacity_compiles() {
        // It used to be refused with an honest reason. The reason stopped
        // being true once the VM tracked the backing array's size, so the
        // refusal had to go with it.
        let result = compile(&[SourceFile {
            path: String::from("Main.java"),
            text: String::from(
                "class Main { static void run() { int c = new StringBuilder().capacity(); } }",
            ),
        }]);
        assert!(result.success(), "{:?}", result.diagnostics);
    }

    /// The honest-reason table is keyed by class: a `File` method must not
    /// borrow the explanation written for the `String` method of that name.
    #[test]
    fn the_unsupported_reason_does_not_leak_across_classes() {
        let result = compile(&[SourceFile {
            path: String::from("Main.java"),
            text: String::from(
                "import java.io.File; \
                 class Main { static void run() { new File(\"a\").matches(\"b\"); } }",
            ),
        }]);
        assert!(!result.success());
        let message = &result.diagnostics[0].message;
        assert!(
            message.contains("cannot find symbol") && !message.contains("String.matches"),
            "got: {message}"
        );
    }

    #[test]
    fn unsupported_features_fail_with_friendly_messages() {
        // Valid Java the engine does not implement says so, which is how the
        // corpus tooling tells an engine gap from a mistake in the source.
        // (`synchronized` was the example here until it became a no-op with a
        // null check, which is what it means on one thread.)
        let result = compile(&[SourceFile {
            path: String::from("Main.java"),
            text: String::from("class Main { static void run() { java.util.Vector<Integer> v; } }"),
        }]);
        assert!(!result.success());
        assert!(result.classes.is_empty());
        assert!(
            result.diagnostics[0]
                .message
                .contains("not supported by caturra"),
            "got: {}",
            result.diagnostics[0].message
        );
    }
}
