//! The `javac`-equivalent half of caturra: compiles Java 11 source (the
//! AP Computer Science A subset) to JVM class files.
//!
//! Pipeline: [`lexer`] → [`parser`] (AST) → [`codegen`]
//! ([`caturra_classfile::ClassFile`]). The supported language surface and
//! its staging plan live in `specs/LANGUAGE.md`; constructs beyond the
//! current stage produce friendly "not yet supported" diagnostics.

pub mod ast;
mod capture;
pub mod codegen;
pub mod diagnostics;
mod imports;
mod lambda;
pub mod lexer;
mod mock;
pub mod parser;

use std::collections::HashMap;
use std::fmt::Write as _;

use caturra_classfile::ClassFile;

pub use diagnostics::{Diagnostic, Severity, SourcePosition, SourceSpan};

/// One Java source file presented to the compiler.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SourceFile {
    /// Path of the file, e.g. `Main.java` or `com/example/Main.java`.
    pub path: String,
    /// Full source text.
    pub text: String,
}

/// A compiled class, ready to be loaded by the VM or written to the
/// virtual filesystem as a `.class` file.
#[derive(Debug, Clone, PartialEq)]
pub struct CompiledClass {
    /// Binary class name, e.g. `com/example/Main`.
    pub binary_name: String,
    pub class_file: ClassFile,
}

/// The result of compiling a set of source files. Compilation is
/// all-or-nothing: if any error-severity diagnostic is present,
/// `classes` is empty.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct Compilation {
    pub classes: Vec<CompiledClass>,
    pub diagnostics: Vec<Diagnostic>,
    /// Entry class for a validation ("Test") run — set when `JUnit` `@Test`
    /// methods were found and a synthetic runner was injected. Run this
    /// class's `main` instead of the student's to execute the tests.
    pub validation_entry: Option<String>,
}

impl Compilation {
    /// Whether compilation succeeded (no error-severity diagnostics).
    #[must_use]
    pub fn success(&self) -> bool {
        self.diagnostics
            .iter()
            .all(|d| d.severity != Severity::Error)
    }
}

/// Bundled clean-room implementation of `org.code.neighborhood`,
/// injected when a source imports that package.
const NEIGHBORHOOD_LIB: &str = include_str!("stdlib/neighborhood.java");

/// Bundled clean-room implementation of `org.code.theater` and
/// `org.code.media`, injected when either package is imported.
const THEATER_LIB: &str = include_str!("stdlib/theater.java");

/// Bundled clean-room `javax.swing` / `java.awt` subset, injected when
/// either package is imported. The component tree serializes to the VFS
/// file `swing.json`, which the playground renders as accessible DOM.
const SWING_LIB: &str = include_str!("stdlib/swing.java");

/// Bundled `org.junit.jupiter.api.Assertions` subset, injected when a
/// source imports `org.junit` (the validation "Test" mode).
const JUNIT_LIB: &str = include_str!("stdlib/junit.java");

/// Bundled `java.util.Arrays` subset (`toString`), injected when a source
/// imports `java.util` — element concatenation coerces each via `toString`.
const ARRAYS_LIB: &str = include_str!("stdlib/arrays.java");

/// Bundled `java.lang.reflect.Modifier` subset, injected when a source uses
/// `Modifier.` (the access-flag decoder used by reflection validators).
const REFLECT_LIB: &str = include_str!("stdlib/reflect.java");

/// Bundled `java.util` helpers (`Random`, `Collections`), injected when a
/// source references `Random`/`Collections`.
const UTIL_LIB: &str = include_str!("stdlib/util.java");

/// The erased `__BiConsumer` target type of a `Map.forEach` lambda,
/// injected when a source calls `forEach`.
const FUNCTION_LIB: &str = include_str!("stdlib/function.java");

/// Bundled `org.code.validation` (test harness helpers), injected when a
/// source imports it: `SystemOutTestRunner`, `ValidationHelper`, and the
/// neighborhood log types.
const VALIDATION_LIB: &str = include_str!("stdlib/validation.java");

/// `NeighborhoodTestRunner`, injected only when `org.code.neighborhood` is
/// also imported (it reads `__NbhdWorld`'s action log).
const VALIDATION_NEIGHBORHOOD_LIB: &str = include_str!("stdlib/validation_neighborhood.java");

/// Bundled minimal `EasyMock` (partial mocks + record/replay/verify), injected
/// when a source imports `org.easymock`. The mock subclasses are generated by
/// the [`mock`] rewrite; this provides the engine and static API.
const EASYMOCK_LIB: &str = include_str!("stdlib/easymock.java");

/// A discovered `@Test` method for the synthetic validation runner.
struct TestCase {
    method: String,
    display: String,
    order: i32,
}

/// A test class: its `@BeforeAll`/`@BeforeEach` setup methods and ordered
/// `@Test`s.
struct TestClass {
    name: String,
    before_all: Vec<String>,
    before_each: Vec<String>,
    tests: Vec<TestCase>,
}

/// Collect `JUnit` `@Test` methods (with `@Order`/`@DisplayName`/`@BeforeEach`)
/// from the user's classes.
fn collect_tests(units: &[(String, ast::CompilationUnit)]) -> Vec<TestClass> {
    let mut classes = Vec::new();
    for (_, unit) in units {
        for class in &unit.classes {
            let has = |m: &ast::MethodDecl, n: &str| m.annotations.iter().any(|a| a.name == n);
            let before_all: Vec<String> = class
                .methods
                .iter()
                .filter(|m| has(m, "BeforeAll"))
                .map(|m| m.name.clone())
                .collect();
            let before_each: Vec<String> = class
                .methods
                .iter()
                .filter(|m| has(m, "BeforeEach"))
                .map(|m| m.name.clone())
                .collect();
            let mut tests: Vec<TestCase> = class
                .methods
                .iter()
                .filter(|m| has(m, "Test"))
                .map(|m| {
                    let order = m
                        .annotations
                        .iter()
                        .find(|a| a.name == "Order")
                        .and_then(|a| a.int_arg)
                        .unwrap_or(i32::MAX);
                    // The label a student reads in the results panel, and JUnit
                    // is fussier about it than it looks. `@DisplayName` is
                    // TRIMMED (JUnit rejects a blank one outright), and without
                    // the annotation the default is `name()` — the parentheses
                    // are part of it. We printed the raw annotation and a bare
                    // method name, so 1721 corpus levels labelled their tests
                    // differently here than on Code.org.
                    let display = m
                        .annotations
                        .iter()
                        .find(|a| a.name == "DisplayName")
                        .and_then(|a| a.str_arg.as_deref())
                        .map(str::trim)
                        .filter(|name| !name.is_empty())
                        .map_or_else(|| format!("{}()", m.name), str::to_owned);
                    TestCase {
                        method: m.name.clone(),
                        display,
                        order,
                    }
                })
                .collect();
            tests.sort_by_key(|t| t.order);
            if !tests.is_empty() {
                classes.push(TestClass {
                    name: class.name.clone(),
                    before_all,
                    before_each,
                    tests,
                });
            }
        }
    }
    classes
}

/// Generate a runner `main` that instantiates each test class, runs its
/// `@BeforeEach` setup and each `@Test`, and prints one
/// `__VTEST\t<PASS|FAIL>\t<name>\t<message>` line per test.
fn validation_runner_source(classes: &[TestClass]) -> String {
    let mut src = String::from(
        "public class __ValidationRunner {\n  public static void main(String[] args) {\n",
    );
    for class in classes {
        // `@BeforeAll` runs once (static); tolerate failure so per-test
        // errors are still reported individually.
        for setup in &class.before_all {
            src.push_str("    try {\n");
            let _ = writeln!(src, "      {}.{setup}();", class.name);
            src.push_str("    } catch (Throwable __e) {}\n");
        }
        for test in &class.tests {
            let name = test
                .display
                .replace('\\', "\\\\")
                .replace('"', "\\\"")
                .replace(['\t', '\n', '\r'], " ");
            src.push_str("    try {\n");
            let _ = writeln!(src, "      {0} __t = new {0}();", class.name);
            for setup in &class.before_each {
                let _ = writeln!(src, "      __t.{setup}();");
            }
            let _ = writeln!(src, "      __t.{}();", test.method);
            let _ = writeln!(
                src,
                "      System.out.println(\"__VTEST\\tPASS\\t{name}\\t\");"
            );
            src.push_str("    } catch (Throwable __e) {\n");
            let _ = writeln!(
                src,
                "      System.out.println(\"__VTEST\\tFAIL\\t{name}\\t\" + __e.getMessage());"
            );
            src.push_str("    }\n");
        }
    }
    src.push_str("  }\n}\n");
    src
}

/// The student's class names: classes in the original (non-injected) sources
/// that are not `JUnit` validators. `ValidationHelper.getClassNames` reports
/// these so a validator can check the student defined a class by name.
fn student_class_names(units: &[(String, ast::CompilationUnit)]) -> Vec<String> {
    let mut names = Vec::new();
    for (path, unit) in units {
        if path.starts_with('<') {
            continue; // injected bundle / synthetic unit
        }
        let is_validator = unit.imports.iter().any(|import| {
            import.path.first().map(String::as_str) == Some("org")
                && import.path.get(1).map(String::as_str) == Some("junit")
        });
        if is_validator {
            continue;
        }
        for class in &unit.classes {
            names.push(class.name.clone());
        }
    }
    names
}

/// Generate the `__ValidationClasses` companion that backs
/// `ValidationHelper.getClassNames` with a compile-time class-name list.
fn user_classes_source(names: &[String]) -> String {
    let mut src = String::from(
        "class __ValidationClasses {\n  \
         static java.util.ArrayList<String> names() {\n    \
         java.util.ArrayList<String> n = new java.util.ArrayList<String>();\n",
    );
    for name in names {
        // Class names are identifiers, so no escaping is needed.
        let _ = writeln!(src, "    n.add(\"{name}\");");
    }
    src.push_str("    return n;\n  }\n}\n");
    src
}

/// Whether any unit imports something under the given prefix path
/// (`["org","junit"]` matches `import static org.junit.jupiter....`).
fn imports_prefix(units: &[(String, ast::CompilationUnit)], prefix: &[&str]) -> bool {
    units.iter().any(|(_, unit)| {
        unit.imports.iter().any(|import| {
            import.path.len() >= prefix.len() && import.path[..prefix.len()] == *prefix
        })
    })
}

/// Whether any unit imports a class from the given package path
/// (matches both `import pkg.*` and `import pkg.Class`).
fn imports_package(units: &[(String, ast::CompilationUnit)], package: &[&str]) -> bool {
    units.iter().any(|(_, unit)| {
        unit.imports.iter().any(|import| {
            let prefix = if import.wildcard {
                import.path.as_slice()
            } else {
                &import.path[..import.path.len().saturating_sub(1)]
            };
            prefix == package
        })
    })
}

/// Compile a set of Java source files. All files are parsed first so
/// classes can call each other's static methods regardless of file
/// order.
#[must_use]
#[allow(clippy::too_many_lines)] // the bundle-injection pipeline
pub fn compile(sources: &[SourceFile]) -> Compilation {
    let mut compilation = Compilation::default();
    let mut seen: HashMap<String, String> = HashMap::new();
    let mut units = Vec::new();

    for source in sources {
        let (tokens, mut lex_errors) = lexer::lex(&source.path, &source.text);
        compilation.diagnostics.append(&mut lex_errors);

        let (unit, mut parse_errors) = parser::parse(&source.path, tokens);
        compilation.diagnostics.append(&mut parse_errors);

        for class in &unit.classes {
            // JLS §7.6: a public top-level type must be declared in a file
            // named after it. javac enforces this, so a program that ignores
            // it compiles here and fails on a real JDK. Only user files are
            // checked — the bundled libraries declare no public types.
            if class.is_public && !class.is_anonymous && !class.is_nested {
                let base = source
                    .path
                    .rsplit('/')
                    .next()
                    .unwrap_or(&source.path)
                    .strip_suffix(".java");
                if let Some(base) = base
                    && base != class.name
                {
                    let kind = if class.is_interface {
                        "interface"
                    } else if class.is_enum {
                        "enum"
                    } else {
                        "class"
                    };
                    compilation.diagnostics.push(Diagnostic {
                        severity: Severity::Error,
                        message: format!(
                            "{kind} {} is public, should be declared in a file named {}.java",
                            class.name, class.name
                        ),
                        path: source.path.clone(),
                        span: Some(class.span),
                    });
                }
            }
            if let Some(other_path) = seen.get(&class.name) {
                compilation.diagnostics.push(Diagnostic {
                    severity: Severity::Error,
                    message: format!("class '{}' is already defined in {other_path}", class.name),
                    path: source.path.clone(),
                    span: Some(class.span),
                });
            } else {
                seen.insert(class.name.clone(), source.path.clone());
            }
        }
        units.push((source.path.clone(), unit));
    }

    // Auto-inject bundled library sources when their package is
    // imported (e.g. the Code.org neighborhood Painter). Parsed like
    // any other unit so its classes participate in resolution.
    if imports_package(&units, &["org", "code", "neighborhood"]) {
        let (tokens, _) = lexer::lex("<neighborhood>", NEIGHBORHOOD_LIB);
        let (unit, mut errs) = parser::parse("<neighborhood>", tokens);
        compilation.diagnostics.append(&mut errs);
        units.push((String::from("<neighborhood>"), unit));
    }
    // org.code.validation (neighborhood test harness): runs the student's main
    // and reports the recorded action log. Depends on __NbhdWorld above.
    if imports_package(&units, &["org", "code", "validation"]) {
        let (tokens, _) = lexer::lex("<validation-lib>", VALIDATION_LIB);
        let (unit, mut errs) = parser::parse("<validation-lib>", tokens);
        compilation.diagnostics.append(&mut errs);
        units.push((String::from("<validation-lib>"), unit));
        // The neighborhood harness depends on __NbhdWorld; only inject it when
        // the neighborhood library is present too.
        if imports_package(&units, &["org", "code", "neighborhood"]) {
            let (tokens, _) = lexer::lex("<validation-nbhd>", VALIDATION_NEIGHBORHOOD_LIB);
            let (unit, mut errs) = parser::parse("<validation-nbhd>", tokens);
            compilation.diagnostics.append(&mut errs);
            units.push((String::from("<validation-nbhd>"), unit));
        }
        // Bake the student's class names in for `ValidationHelper.getClassNames`
        // (the student sources are the non-injected, non-JUnit units).
        let source = user_classes_source(&student_class_names(&units));
        let (tokens, _) = lexer::lex("<validation-classes>", &source);
        let (unit, mut errs) = parser::parse("<validation-classes>", tokens);
        compilation.diagnostics.append(&mut errs);
        units.push((String::from("<validation-classes>"), unit));
    }
    if imports_package(&units, &["org", "code", "theater"])
        || imports_package(&units, &["org", "code", "media"])
    {
        let (tokens, _) = lexer::lex("<theater>", THEATER_LIB);
        let (unit, mut errs) = parser::parse("<theater>", tokens);
        compilation.diagnostics.append(&mut errs);
        units.push((String::from("<theater>"), unit));
    }
    // javax.swing / java.awt (accessible DOM Swing): the component tree
    // serializes to `swing.json` on `setVisible(true)`.
    if imports_package(&units, &["javax", "swing"])
        || imports_package(&units, &["javax", "swing", "event"])
        || imports_package(&units, &["javax", "swing", "border"])
        || imports_package(&units, &["javax", "swing", "text"])
        || imports_package(&units, &["javax", "accessibility"])
        || imports_package(&units, &["java", "awt"])
        || imports_package(&units, &["java", "awt", "event"])
    {
        let (tokens, _) = lexer::lex("<swing>", SWING_LIB);
        let (unit, mut errs) = parser::parse("<swing>", tokens);
        compilation.diagnostics.append(&mut errs);
        units.push((String::from("<swing>"), unit));
    }
    let mut validation_entry = None;
    if sources.iter().any(|s| s.text.contains("Arrays."))
        && !units
            .iter()
            .any(|(_, unit)| unit.classes.iter().any(|c| c.name == "Arrays"))
    {
        let (tokens, _) = lexer::lex("<arrays>", ARRAYS_LIB);
        let (unit, mut errs) = parser::parse("<arrays>", tokens);
        compilation.diagnostics.append(&mut errs);
        units.push((String::from("<arrays>"), unit));
    }
    if sources.iter().any(|s| s.text.contains("Modifier."))
        && !units
            .iter()
            .any(|(_, unit)| unit.classes.iter().any(|c| c.name == "Modifier"))
    {
        let (tokens, _) = lexer::lex("<reflect>", REFLECT_LIB);
        let (unit, mut errs) = parser::parse("<reflect>", tokens);
        compilation.diagnostics.append(&mut errs);
        units.push((String::from("<reflect>"), unit));
    }
    if (sources.iter().any(|s| s.text.contains("Random"))
        || sources.iter().any(|s| s.text.contains("Collections.")))
        && !units.iter().any(|(_, unit)| {
            unit.classes
                .iter()
                .any(|c| c.name == "Random" || c.name == "Collections")
        })
    {
        let (tokens, _) = lexer::lex("<util>", UTIL_LIB);
        let (unit, mut errs) = parser::parse("<util>", tokens);
        compilation.diagnostics.append(&mut errs);
        units.push((String::from("<util>"), unit));
    }
    if sources.iter().any(|s| {
        s.text.contains(".forEach(")
            || s.text.contains(".removeIf(")
            || s.text.contains(".replaceAll(")
            || s.text.contains(".sort(")
            // `optional.ifPresent(x -> ...)` / `filter(x -> ...)` desugar to the
            // bundled `__Consumer`/`__Predicate` too.
            || s.text.contains(".ifPresent(")
            || s.text.contains(".filter(")
            // `Arrays.setAll(a, i -> ...)` uses the bundled `__UnaryOperator`.
            || s.text.contains(".setAll(")
            // `optional.map(x -> ...)` / `orElseGet(() -> ...)` use the bundled
            // `__UnaryOperator` / `__Supplier`.
            || s.text.contains(".map(")
            || s.text.contains(".orElseGet(")
            // A stream pipeline's `filter`/`map`/… lambdas desugar to the
            // bundled functional interfaces.
            || s.text.contains(".stream(")
            // A user `Comparator` aliases the bundled `__Comparator` interface;
            // `Collections.reverseOrder()` also yields one without naming it.
            || s.text.contains("Comparator")
            || s.text.contains("reverseOrder")
            // A comparator lambda in a sorted collection's constructor
            // (`new PriorityQueue<>((a, b) -> ...)`) needs `__Comparator` too,
            // without ever naming it — trigger on the pair.
            || (s.text.contains("->")
                && (s.text.contains("TreeSet")
                    || s.text.contains("TreeMap")
                    || s.text.contains("PriorityQueue")))
    }) && !units
        .iter()
        .any(|(_, unit)| unit.classes.iter().any(|c| c.name == "__BiConsumer"))
    {
        let (tokens, _) = lexer::lex("<function>", FUNCTION_LIB);
        let (unit, mut errs) = parser::parse("<function>", tokens);
        compilation.diagnostics.append(&mut errs);
        units.push((String::from("<function>"), unit));
    }
    if imports_prefix(&units, &["org", "junit"]) {
        let (tokens, _) = lexer::lex("<junit>", JUNIT_LIB);
        let (unit, mut errs) = parser::parse("<junit>", tokens);
        compilation.diagnostics.append(&mut errs);
        units.push((String::from("<junit>"), unit));
        // Synthesize a runner that executes the discovered @Test methods.
        let tests = collect_tests(&units);
        if !tests.is_empty() {
            let source = validation_runner_source(&tests);
            let (tokens, _) = lexer::lex("<validation>", &source);
            let (unit, mut errs) = parser::parse("<validation>", tokens);
            compilation.diagnostics.append(&mut errs);
            units.push((String::from("<validation>"), unit));
            validation_entry = Some(String::from("__ValidationRunner"));
        }
    }

    // EasyMock partial mocks: inject the engine, then rewrite each
    // `partialMockBuilder(T.class)….createMock()` chain into a generated
    // `new __EMock_T_…()` subclass (before codegen or import checks see them).
    if imports_prefix(&units, &["org", "easymock"]) {
        let (tokens, _) = lexer::lex("<easymock>", EASYMOCK_LIB);
        let (unit, mut errs) = parser::parse("<easymock>", tokens);
        compilation.diagnostics.append(&mut errs);
        units.push((String::from("<easymock>"), unit));
        if let Some(source) = mock::rewrite(&mut units) {
            let (tokens, _) = lexer::lex("<mocks>", &source);
            let (unit, mut errs) = parser::parse("<mocks>", tokens);
            compilation.diagnostics.append(&mut errs);
            units.push((String::from("<mocks>"), unit));
        }
    }

    // Import validation and enforcement (after all units parse, since
    // user classes anywhere in the compilation shadow library names).
    let user_classes: std::collections::HashSet<String> = units
        .iter()
        .flat_map(|(_, unit)| unit.classes.iter().map(|c| c.name.clone()))
        .collect();
    for (path, unit) in &units {
        imports::check_unit(path, unit, &user_classes, &mut compilation.diagnostics);
    }

    lambda::desugar_lambdas(&mut units);
    compilation
        .diagnostics
        .extend(capture::resolve_captures(&mut units));
    let (classes, mut codegen_errors) = codegen::generate(&units);
    compilation.diagnostics.append(&mut codegen_errors);

    if compilation.success() {
        compilation.classes = classes;
        compilation.validation_entry = validation_entry;
    }
    compilation
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn lexical_errors_are_reported_with_positions() {
        let result = compile(&[SourceFile {
            path: String::from("Main.java"),
            text: String::from("class Main { char c = 'x; }"),
        }]);
        assert!(!result.success());
        assert!(result.classes.is_empty());
        let error = &result.diagnostics[0];
        assert_eq!(error.path, "Main.java");
        assert!(
            error.message.contains("character literal"),
            "{}",
            error.message
        );
    }

    #[test]
    fn structural_reflection_compiles() {
        // The `AttributesHelper` surface: getClass / getSimpleName /
        // getSuperclass / getDeclaredFields + Arrays.toString(Field[]).
        let result = compile(&[
            SourceFile {
                path: String::from("Dog.java"),
                text: String::from("public class Dog { private String name; private int age; }"),
            },
            SourceFile {
                path: String::from("Main.java"),
                text: String::from(
                    r#"
                    import java.lang.reflect.*;
                    import java.util.*;
                    public class Main {
                        public static void main(String[] args) {
                            Object o = new Dog();
                            Class c = o.getClass();
                            String n = c.getSimpleName();
                            Class sup = c.getSuperclass();
                            Field[] fields = c.getDeclaredFields();
                            System.out.println(n + " extends " + sup.getSimpleName());
                            System.out.println(Arrays.toString(fields));
                        }
                    }
                    "#,
                ),
            },
        ]);
        assert!(result.success(), "{:?}", result.diagnostics);
    }

    #[test]
    fn hello_world_compiles_to_a_class() {
        let result = compile(&[SourceFile {
            path: String::from("Main.java"),
            text: String::from(
                r#"
                public class Main {
                    public static void main(String[] args) {
                        System.out.println("Hello, World!");
                    }
                }
                "#,
            ),
        }]);
        assert!(result.success(), "{:?}", result.diagnostics);
        assert_eq!(result.classes.len(), 1);
        assert_eq!(result.classes[0].binary_name, "Main");
        // The class file is structurally valid: it round-trips.
        let bytes = caturra_classfile::write_class_file(&result.classes[0].class_file);
        let parsed = caturra_classfile::read_class_file(&bytes).expect("valid class file");
        assert_eq!(parsed.class_name(), Some("Main"));
    }

    #[test]
    fn duplicate_classes_across_files_are_reported() {
        let result = compile(&[
            SourceFile {
                path: "A.java".into(),
                text: "class Main { }".into(),
            },
            SourceFile {
                path: "B.java".into(),
                text: "class Main { }".into(),
            },
        ]);
        assert!(!result.success());
        assert!(
            result.diagnostics[0]
                .message
                .contains("already defined in A.java")
        );
    }

    /// caturra targets the Java 11 subset, so an API added later must be
    /// rejected exactly as javac 11 rejects it. Accepting it would be worse than
    /// missing it: the student's code compiles here and fails on a real JDK.
    #[test]
    fn post_java_11_apis_are_not_offered() {
        // Math.absExact is Java 15; Random.nextInt(origin, bound) is Java 17.
        // Both messages match what javac 11 prints for the same source.
        let cases = [
            (
                "class Main { static void run() { int x = Math.absExact(-5); } }",
                "cannot find symbol",
            ),
            (
                "import java.util.Random; \
                 class Main { static void run() { int x = new Random(1).nextInt(2, 5); } }",
                "no suitable method found for nextInt(int,int)",
            ),
        ];
        for (source, want) in cases {
            let result = compile(&[SourceFile {
                path: String::from("Main.java"),
                text: String::from(source),
            }]);
            assert!(!result.success(), "should not compile: {source}");
            let message = &result.diagnostics[0].message;
            assert!(message.contains(want), "expected {want:?}, got: {message}");
        }
    }

    /// A real Java 11 member caturra cannot model says so, rather than
    /// pretending it never existed.
    #[test]
    fn string_builder_capacity_explains_itself() {
        let result = compile(&[SourceFile {
            path: String::from("Main.java"),
            text: String::from(
                "class Main { static void run() { int c = new StringBuilder().capacity(); } }",
            ),
        }]);
        assert!(!result.success());
        assert_eq!(
            result.diagnostics[0].message,
            "StringBuilder.capacity exists in Java, but caturra does not model a builder's \
             capacity, only its contents"
        );
    }

    /// The honest-reason table is keyed by class: a `File` method must not
    /// borrow the explanation written for the `String` method of that name.
    #[test]
    fn the_unsupported_reason_does_not_leak_across_classes() {
        let result = compile(&[SourceFile {
            path: String::from("Main.java"),
            text: String::from(
                "import java.io.File; \
                 class Main { static void run() { new File(\"a\").matches(\"b\"); } }",
            ),
        }]);
        assert!(!result.success());
        let message = &result.diagnostics[0].message;
        assert!(
            message.contains("cannot find symbol") && !message.contains("String.matches"),
            "got: {message}"
        );
    }

    #[test]
    fn unsupported_features_fail_with_friendly_messages() {
        let result = compile(&[SourceFile {
            path: String::from("Main.java"),
            text: String::from("class Main { static void run() { synchronized (x) { } } }"),
        }]);
        assert!(!result.success());
        assert!(result.classes.is_empty());
        assert!(
            result.diagnostics[0]
                .message
                .contains("not supported by caturra")
        );
    }
}
